### ISSUE TITLE
Ashihara Royal Tomb - Near memory circle mural

### ISSUE THREAD

**Issue by muxles** [lifebottle/Tales-of-Innocence-R#30]
![2021-10-30-121256-221592](https://user-images.githubusercontent.com/8575138/139553943-3e95ea76-4627-4416-a4fb-8cda1bc6228b.png)

**Comment by FistingUranus** [comment]
![030testoutnew](https://user-images.githubusercontent.com/77898683/139554197-f29e070a-ca41-42a6-8474-3122d06b22d1.png)
Extracted and Translated, will be eventually in the patch. you should join the discord for feature proofreading issues.
